apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: monitoring/alertmanager
        property: slack_webhook_url
