apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/manifest-generate-paths: /gitops/platform-values/backstage.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 2.10.0
      helm:
        releaseName: backstage
        valueFiles:
          - $values/gitops/platform-values/backstage.yaml
    - repoURL: https://github.com/beowolf23/infrastructure.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
