apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/manifest-generate-paths: /gitops/platform-values/external-secrets.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.5
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/gitops/platform-values/external-secrets.yaml
    - repoURL: https://github.com/beowolf23/infrastructure.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
