apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
    argocd.argoproj.io/manifest-generate-paths: /gitops/platform-values/loki.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.3.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/gitops/platform-values/loki.yaml
    - repoURL: https://github.com/beowolf23/infrastructure.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
