apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
    argocd.argoproj.io/manifest-generate-paths: /gitops/config/namespaces
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/beowolf23/infrastructure.git
    targetRevision: main
    path: gitops/config/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: false      # never auto-delete a namespace full of workloads
      selfHeal: true
